import { library } from '@fortawesome/fontawesome-svg-core';
import {faNewspaper, 
        faFlag, 
        faSquare, 
        faIdCard, 
        faListOl, 
        faListUl, 
        faWindowRestore, 
        faTv,
        faTh,
        faImage,
        faPlug,
        faLightbulb,
        faShareAlt,
        faStar,
        faFlagCheckered,
        faUtensils,
        faShare,
        faGripLines,
        faCheck,
        faBars
        
    } from '@fortawesome/free-solid-svg-icons';

    library.add(
        faBars,
        faGripLines,
        faCheck,
        faShare,
        faUtensils,
        faNewspaper, 
        faFlag, 
        faSquare, 
        faIdCard, 
        faListOl, 
        faListUl, 
        faWindowRestore, 
        faTv,
        faTh,
        faImage,
        faPlug,
        faLightbulb,
        faShareAlt,
        faStar,
        faFlagCheckered
        )